"input_path": {
    "structures": [
        {
            "micro-prompt": {
                "Sm": 1,
                "Fe": 12,
                "N": 1
            },
            "data_path": "example/Sm1Fe12/micro-prompt/structures.csv"
        }
    ],
    "candidates": "example/Sm1Fe12/micro-prompt/candidates.csv",
    "fe_threshold": 0.070463
},
"output_path": "example/Sm1Fe12/micro-prompt/output",
"acquisition_function": "belief_utility",
"learn": {
    "alpha": 0.001,
    "ers_version": "v5",
    "tuned_parameters": [
        {
            "alpha": [0.001]
        }
    ],
    "list_of_elements": [
        'Sm', 'Fe', 'B', 'C', 'N'
        'SYMM_1', 'SYMM_2', 'SYMM_3', 'SYMM_4', 'SYMM_5', 'SYMM_6', 'SYMM_7', 'SYMM_8', 'SYMM_9', 'SYMM_10', 
        'SYMM_11', 'SYMM_12', 'SYMM_13', 'SYMM_14', 'SYMM_15', 'SYMM_16', 'SYMM_17', 'SYMM_18', 'SYMM_19', 'SYMM_20', 'SYMM_21', 
        'SYMM_22', 'SYMM_23', 'SYMM_24', 'SYMM_25', 'SYMM_26', 'SYMM_27', 'SYMM_28', 'SYMM_29', 'SYMM_30', 'SYMM_31', 'SYMM_32', 
        'SYMM_33', 'SYMM_34', 'SYMM_35', 'SYMM_36', 'SYMM_37', 'SYMM_38', 'SYMM_39', 'SYMM_40', 'SYMM_41', 'SYMM_42', 'SYMM_43', 
        'SYMM_44', 'SYMM_45', 'SYMM_46', 'SYMM_47', 'SYMM_48', 'SYMM_49', 'SYMM_50', 'SYMM_51', 'SYMM_52', 'SYMM_53', 'SYMM_54', 
        'SYMM_55', 'SYMM_56', 'SYMM_57', 'SYMM_58', 'SYMM_59', 'SYMM_60', 'SYMM_61', 'SYMM_62', 'SYMM_63', 'SYMM_64', 'SYMM_65', 
        'SYMM_66', 'SYMM_67', 'SYMM_68', 'SYMM_69', 'SYMM_70', 'SYMM_71', 'SYMM_72', 'SYMM_73', 'SYMM_74', 'SYMM_75', 'SYMM_76', 
        'SYMM_77', 'SYMM_78', 'SYMM_79', 'SYMM_80', 'SYMM_81', 'SYMM_82', 'SYMM_83', 'SYMM_84', 'SYMM_85', 'SYMM_86', 'SYMM_87', 
        'SYMM_88', 'SYMM_89', 'SYMM_90', 'SYMM_91', 'SYMM_92', 'SYMM_93', 'SYMM_94', 'SYMM_95', 'SYMM_96', 'SYMM_97', 'SYMM_98', 
        'SYMM_99', 'SYMM_100', 'SYMM_101', 'SYMM_102', 'SYMM_103', 'SYMM_104', 'SYMM_105', 'SYMM_106', 'SYMM_107', 'SYMM_108', 'SYMM_109', 
        'SYMM_110', 'SYMM_111', 'SYMM_112', 'SYMM_113', 'SYMM_114', 'SYMM_115', 'SYMM_116', 'SYMM_117', 'SYMM_118', 'SYMM_119', 'SYMM_120', 
        'SYMM_121', 'SYMM_122', 'SYMM_123', 'SYMM_124', 'SYMM_125', 'SYMM_126', 'SYMM_127', 'SYMM_128', 'SYMM_129', 'SYMM_130', 'SYMM_131', 
        'SYMM_132', 'SYMM_133', 'SYMM_134', 'SYMM_135', 'SYMM_136', 'SYMM_137', 'SYMM_138', 'SYMM_139', 'SYMM_140', 'SYMM_141', 'SYMM_142', 
        'SYMM_143', 'SYMM_144', 'SYMM_145', 'SYMM_146', 'SYMM_147', 'SYMM_148', 'SYMM_149', 'SYMM_150', 'SYMM_151', 'SYMM_152', 'SYMM_153', 
        'SYMM_154', 'SYMM_155', 'SYMM_156', 'SYMM_157', 'SYMM_158', 'SYMM_159', 'SYMM_160', 'SYMM_161', 'SYMM_162', 'SYMM_163', 'SYMM_164', 
        'SYMM_165', 'SYMM_166', 'SYMM_167', 'SYMM_168', 'SYMM_169', 'SYMM_170', 'SYMM_171', 'SYMM_172', 'SYMM_173', 'SYMM_174', 'SYMM_175', 
        'SYMM_176', 'SYMM_177', 'SYMM_178', 'SYMM_179', 'SYMM_180', 'SYMM_181', 'SYMM_182', 'SYMM_183', 'SYMM_184', 'SYMM_185', 'SYMM_186', 
        'SYMM_187', 'SYMM_188', 'SYMM_189', 'SYMM_190', 'SYMM_191', 'SYMM_192', 'SYMM_193', 'SYMM_194', 'SYMM_195', 'SYMM_196', 'SYMM_197', 
        'SYMM_198', 'SYMM_199', 'SYMM_200', 'SYMM_201', 'SYMM_202', 'SYMM_203', 'SYMM_204', 'SYMM_205', 'SYMM_206', 'SYMM_207', 'SYMM_208', 
        'SYMM_209', 'SYMM_210', 'SYMM_211', 'SYMM_212', 'SYMM_213', 'SYMM_214', 'SYMM_215', 'SYMM_216', 'SYMM_217', 'SYMM_218', 'SYMM_219', 
        'SYMM_220', 'SYMM_221', 'SYMM_222', 'SYMM_223', 'SYMM_224', 'SYMM_225', 'SYMM_226', 'SYMM_227', 'SYMM_228', 'SYMM_229', 'SYMM_230'
    ],
    "target_variable": "Label"
}